# Generated by Django 2.2 on 2021-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
    ]
